name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y iverilog python3

    - name: Run SVT sanity check
      run: make svt

    - name: Run Regression Suite
      run: make regression
